services:
  - type: web
    name: skincare
    env: python
    build:
      buildCommand: |
        pip install -r requirements.txt
        python manage.py collectstatic --noinput
    startCommand: "gunicorn -c gunicorn_config.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: DJANGO_SETTINGS_MODULE
        value: skincare.settings
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 10000
      - key: DISABLE_COLLECTSTATIC
        value: 1
    plan: free
