services:
  - type: web
    name: skincare-ai
    env: python
    build:
      buildCommand: "pip install -r requirements.txt && cd frontend && npm install && npm run build && cd .."
      startCommand: "gunicorn -c gunicorn_config.py skincare_ai.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DISABLE_COLLECTSTATIC
        value: 1
      - key: DJANGO_SETTINGS_MODULE
        value: skincare_ai.settings
      - key: PORT
        value: 10000
    plan: free
